version: '3.1'

services:
  ncmbot-client:
    image: bennythink/ncmbot
    restart: on-failure
    working_dir: /NCMBot/ncmbot
    env_file:
      - env/ncmbot.env
    volumes:
      - ./data/client.session:/NCMBot/ncmbot/client.session
    command: [ "/usr/local/bin/python","client.py" ]

  ncmbot-bot:
    image: bennythink/ncmbot
    env_file:
      - env/ncmbot.env
    volumes:
      - ./data/bot.session:/NCMBot/ncmbot/bot.session
    restart: on-failure
    working_dir: /NCMBot/ncmbot
    command: [ "/usr/local/bin/python","bot.py" ]

  archiver:
    image: bennythink/archiver
    restart: on-failure
    env_file:
      - env/archiver.env

  yyets:
    image: bennythink/yyetsbot
    restart: on-failure
    env_file:
      - env/yyets.env
    volumes:
      - ./data/yyets.dbm:/YYeTsBot/data/yyets.dbm
      - ./data/yyets.dump:/YYeTsBot/data/cookies.dump

  teletweet: # this is only for bot
    image: bennythink/teletweet
    restart: on-failure
    volumes:
      - ./data/teletweet.enc:/TeleTweet/teletweet/database.enc
    env_file:
      - env/teletweet.env

  gakki:
    image: bennythink/dailygakki
    restart: on-failure
    volumes:
      - ./data/gakki.json:/database.json
      - /home/photos/:/photos/
    env_file:
      - env/gakki.env

  keepme-docker:
    image: docker:dind
    restart: on-failure
    environment:
      DOCKER_TLS_CERTDIR:
    privileged: true

  keepme-runner:
    image: bennythink/keepmebot
    environment:
      DOCKER_HOST: tcp://keepme-docker:2375
    env_file:
      - env/keepme.env
    restart: on-failure
    depends_on:
      - keepme-docker
    volumes:
      - ./data/keep.db:/keep.db

  socat:
    image: alpine/socat
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "socat", "tcp-listen:2375,fork,reuseaddr","unix-connect:/var/run/docker.sock" ]

  rssbot:
    build:
      context: .
      dockerfile: docker/rssbot/Dockerfile
    restart: on-failure
    volumes:
      - ./data/rssbot.json:/database.json
    env_file:
      - env/rssbot.env

  wp-comments:
    image: bennythink/wp-comments
    restart: on-failure
    volumes:
      - ./data/wp.json:/config.json
